# Site settings
title: Chris Toumping Fotso
url: "http://chriscmr.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
  Chris Fotso, future Data scientist and mathematician that you need.

# Your information
email: your_email@example.com
author: Chris Toumping Fotso
avatar: "https://github.com/chriscmr/chriscmr.github.io/blob/gh-pages/photos/Chris%20Toumping%20FOTSO-MSc%20in%20Mathematics-Cameroon.jpg?raw=true"
profile: I'm Chris welcome to my site.
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "mailto:toumping.fotso@aims.ac.rw"
  GitHub: "https://github.com/chriscmr"
  Linkedin: "linkedin.com/in/toumping-fotso-5a1b2921b"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    #Category: /category/
    #Donate: https://laobubu.net/donate.html

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
